import type { ProductCardData } from '@pages/home/types/response';

export const mockProducts: ProductCardData[] = [
  {
    productId: 1,
    productName: '무선 청소기',
    discountRate: 20,
    discountPrice: 159000,
    productImage: 'https://dummyimage.com/300x300/cccccc/000000&text=Product+Image',
    reviewCount: 124,
    productTag: 'HIGH_REPURCHASE',
    categoryList: ['recommend', 'digital'],
  },
  {
    productId: 2,
    productName: '아기 물티슈',
    discountRate: 10,
    discountPrice: 4500,
    productImage: 'https://dummyimage.com/300x300/cccccc/000000&text=Product+Image',
    reviewCount: 89,
    productTag: 'LOW_RETURN',
    categoryList: ['recommend', 'baby', 'necessity'],
  },
  {
    productId: 3,
    productName: '실리콘 조리도구 세트',
    discountRate: 15,
    discountPrice: 12900,
    productImage: 'https://dummyimage.com/300x300/cccccc/000000&text=Product+Image',
    reviewCount: 51,
    productTag: 'ESTABLISHED_YEAR_AGO',
    categoryList: ['recommend', 'kitchen'],
  },
  {
    productId: 4,
    productName: '차량용 공기청정기',
    discountRate: 25,
    discountPrice: 34900,
    productImage: 'https://dummyimage.com/300x300/cccccc/000000&text=Product+Image',
    reviewCount: 202,
    productTag: 'NONE',
    categoryList: ['recommend', 'car', 'goods'],
  },
  {
    productId: 5,
    productName: '헬스 아령 세트',
    discountRate: 18,
    discountPrice: 23900,
    productImage: 'https://dummyimage.com/300x300/cccccc/000000&text=Product+Image',
    reviewCount: 77,
    productTag: 'HIGH_REPURCHASE',
    categoryList: ['recommend', 'sport'],
  },
];
